blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [path("", cache_page(60)(BlogListView.as_view()), name="blog_page")]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView, ClientUpdateView

app_name = ClientsConfig.name

urlpatterns = [
    path("", cache_page(60)(ClientListView.as_view()), name="clients_page"),
    path("view_client/<int:pk>/", ClientDetailView.as_view(), name="view_client"),
    path("add_client/", ClientCreateView.as_view(), name="add_client"),
    path("update_client/<int:pk>/", ClientUpdateView.as_view(), name="update_client"),
    path("delete_client/<int:pk>/", ClientDeleteView.as_view(), name="delete_client"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("letters/", include("letters.urls", namespace="letters")),
    path("logstatus/", include("logstatus.urls", namespace="logstatus")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letters/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from letters.apps import MessagesConfig
from letters.views import LetterCreateView, LetterDeleteView, LetterDetailView, LetterListView, LetterUpdateView

app_name = MessagesConfig.name

urlpatterns = [
    path("", cache_page(60)(LetterListView.as_view()), name="letters_page"),
    path("view_letter/<int:pk>/", LetterDetailView.as_view(), name="view_letter"),
    path("add_letter/", LetterCreateView.as_view(), name="add_letter"),
    path("update_letter/<int:pk>/", LetterUpdateView.as_view(), name="update_letter"),
    path("delete_letter/<int:pk>/", LetterDeleteView.as_view(), name="delete_letter"),
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    toggle_activity,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", cache_page(60)(MailingListView.as_view()), name="mailing_page"),
    path("view_mailing/<int:pk>/", MailingDetailView.as_view(), name="view_mailing"),
    path("add_mailing/", MailingCreateView.as_view(), name="add_mailing"),
    path("update_mailing/<int:pk>/", MailingUpdateView.as_view(), name="update_mailing"),
    path("delete_mailing/<int:pk>/", MailingDeleteView.as_view(), name="delete_mailing"),
    path("activity/<int:pk>/", toggle_activity, name="toggle_activity"),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileView, RegisterView, RestorePassword, Verification, logout_view

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("verification/", Verification.as_view(), name="verification"),
    path("restore_password/", RestorePassword.as_view(), name="restore_password"),
]

website/urls.py
from django.urls import path

from website.apps import WebsiteConfig
from website.views import ManagerListView, WebsiteListView, toggle_activity

app_name = WebsiteConfig.name

urlpatterns = [
    path("", WebsiteListView.as_view(), name="homepage"),
    path("manager/", ManagerListView.as_view(), name="manager"),
    path("activity/<int:pk>/", toggle_activity, name="managerpage"),
]

website/forms.py
import typing


class StyleFormMixin:
    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            if field_name == "is_active":
                field.widget.attrs["class"] = "form-check-input"

website/views.py
import typing

from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView

from blog.models import Blog
from mailing.services import get_cache_clients_count, get_cache_mailing_active, get_cache_mailing_count
from users.models import User


class WebsiteListView(ListView):
    """Контроллер для просмотра сущностей"""

    model = Blog
    template_name = "website/homepage.html"

    def get_queryset(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        queryset = super().get_queryset(*args, **kwargs)
        return queryset.order_by("?")[:3]

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)

        context["title"] = "Главная страница"
        context["mailing_amount"] = get_cache_mailing_count()
        context["mailing_active"] = get_cache_mailing_active()
        context["clients_amount"] = get_cache_clients_count()
        return context


class ManagerListView(UserPassesTestMixin, ListView):
    """Контроллер для просмотра сущностей"""

    model = User
    template_name = "website/manager.html"

    def test_func(self) -> typing.Any:
        return self.request.user.is_staff

    def get_queryset(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(is_staff=False)
        return queryset


def toggle_activity(request: typing.Any, pk: int) -> typing.Any:
    """Контроллер для изменения статуса сущности"""
    user_activity = get_object_or_404(User, pk=pk)
    if user_activity.is_active:
        user_activity.is_active = False
    else:
        user_activity.is_active = True
    user_activity.save()

    return redirect(reverse("website:manager"))

website/templates/website/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94"
             role="img"><title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                  fill="currentColor"></path>
        </svg>
        <span class="fs-4">Управление рассылками</span>
    </a>
    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'website:homepage' %}">Главная</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'clients:clients_page' %}">Клиенты</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'letters:letters_page' %}">Письма</a>
        <a class="py-2 text-dark text-decoration-none" href="{% url 'mailing:mailing_page' %}">Рассылки</a>
    </nav>
    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if user.is_superuser or user.is_staff %}
        <a class="me-3 py-2 text-success text-decoration-underline" href="/admin">Админка</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="me-3 py-2 text-success text-decoration-underline" href="{% url 'users:profile' %}">Профиль</a>
        <a class="me-3 py-2 text-success text-decoration-underline" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="me-3 py-2 text-warning text-decoration-none" href="{% url 'users:login' %}">Войти</a>
        <a class="me-3 py-2 text-warning text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>