blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [path("", cache_page(60)(BlogListView.as_view()), name="blog_page")]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("letters/", include("letters.urls", namespace="letters")),
    path("logstatus/", include("logstatus.urls", namespace="logstatus")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logstatus/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from logstatus.apps import LogstatusConfig
from logstatus.views import LogMessageListView

app_name = LogstatusConfig.name

urlpatterns = [path("view_log/<int:pk>/", cache_page(60)(LogMessageListView.as_view()), name="logs_page")]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    toggle_activity,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", cache_page(60)(MailingListView.as_view()), name="mailing_page"),
    path("view_mailing/<int:pk>/", MailingDetailView.as_view(), name="view_mailing"),
    path("add_mailing/", MailingCreateView.as_view(), name="add_mailing"),
    path("update_mailing/<int:pk>/", MailingUpdateView.as_view(), name="update_mailing"),
    path("delete_mailing/<int:pk>/", MailingDeleteView.as_view(), name="delete_mailing"),
    path("activity/<int:pk>/", toggle_activity, name="toggle_activity"),
]

mailing/models.py
from django.conf import settings
from django.db import models

from clients.models import Client
from config.settings import NULLABLE, PERIOD_CHOICES, STATUS_CHOICES
from letters.models import Letter


class Mailing(models.Model):
    """
    Модель Рассылки
    """

    name = models.CharField(max_length=150, verbose_name="Имя рассылки")
    client_emails = models.ManyToManyField(Client, verbose_name="Имэйлы")
    letter = models.ForeignKey(Letter, **NULLABLE, on_delete=models.SET, verbose_name="Письмо")
    first_sending_time = models.DateTimeField(**NULLABLE, verbose_name="Время первой рассылки")
    period = models.CharField(max_length=150, choices=PERIOD_CHOICES, verbose_name="Период")
    start_datetime = models.DateTimeField(**NULLABLE, verbose_name="Время начала")
    end_datetime = models.DateTimeField(**NULLABLE, verbose_name="Время конца")
    created_at = models.DateTimeField(**NULLABLE, auto_now_add=True, verbose_name="Время создания")
    status = models.CharField(
        default="Создана", max_length=20, **NULLABLE, choices=STATUS_CHOICES, verbose_name="Статус"
    )

    next_sending_time = models.DateTimeField(**NULLABLE, verbose_name="Время следующей рассылки")
    is_active = models.BooleanField(default=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self) -> str:
        return (
            f"{self.name}, {self.client_emails}, {self.letter},"
            f"{self.start_datetime}, {self.end_datetime}, {self.created_at},"
            f"{self.first_sending_time}, {self.period}, {self.status}, {self.pk}"
        )

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"

        permissions = [("set_inactive", "Can block mailing")]

mailing/forms.py
from django import forms
from django.forms import DateTimeInput

from mailing.models import Mailing
from website.forms import StyleFormMixin


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = (
            "owner",
            "status",
            "next_sending_time",
        )
        widgets = {
            "first_sending_time": DateTimeInput(attrs={"type": "datetime-local"}),
            "start_datetime": DateTimeInput(attrs={"type": "datetime-local"}),
            "end_datetime": DateTimeInput(attrs={"type": "datetime-local"}),
        }
        labels = {
            "sending_time": "Время рассылки",
            "start_datetime": "Время начала",
            "end_datetime": "Время конца",
        }

mailing/views.py
import typing

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from mailing.forms import MailingForm
from mailing.models import Mailing


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра сущностей"""

    model = Mailing
    login_url = reverse_lazy("website:homepage")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Рассылки"
        return context

    def get_queryset(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.groups.filter(name="manager") or user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingDetailView(DetailView):
    """Контроллер для просмотра сущности"""

    model = Mailing

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.owner != user and not user.groups.filter(name="manager"):
            raise Http404("Доступ запрещен")
        return self.object

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.name
        return context


class MailingCreateView(CreateView):
    """Контроллер для создания сущности"""

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_page")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Добавление рассылки"
        return context

    def form_valid(self, form: typing.Any) -> typing.Any:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self) -> typing.Any:
        return not self.request.user.groups.filter(name="manager")


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для изменения сущности"""

    model = Mailing
    form_class = MailingForm
    login_url = reverse_lazy("website:homepage")

    def get_success_url(self) -> typing.Any:
        return reverse("mailing:view_mailing", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Обновление рассылки"
        return context

    def test_func(self) -> typing.Any:
        custom_perms = ("mailing.set_inactive",)
        if self.request.user.groups.filter(name="manager") and self.request.user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.owner != user:
            raise Http404("Доступ запрещен")
        return self.object


class MailingDeleteView(DeleteView):
    """Контроллер для удаления сущности"""

    model = Mailing
    success_url = reverse_lazy("mailing:mailing_page")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Удаление рассылки"
        return context

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.owner != user:
            raise Http404("Доступ запрещен")
        return self.object


def toggle_activity(request: typing.Any, pk: int) -> typing.Any:
    """Контроллер для изменения статуса сущности"""
    mailing_status = get_object_or_404(Mailing, pk=pk)
    if mailing_status.is_active:
        mailing_status.is_active = False
    else:
        mailing_status.is_active = True
    mailing_status.save()

    return redirect(reverse("mailing:mailing_page"))

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'website/base.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Удаление рассылки</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Точно удаляем {{ object.name|title }}?</p>
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Удалить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'mailing:mailing_page' %}" class="w-100 btn btn-lg btn-outline-primary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'website/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылка: {{ object.name|title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Тема письма: {{ object.letter }}</li>
                    <li>Время рассылки: {{ object.first_sending_time|date:"d/m/Y, H:i" }}</li>
                    <li>Период: {{ object.period }}</li>
                    <li>Время начала: {{ object.start_datetime|date:"d/m/Y, H:i" }}</li>
                    <li>Время конца: {{ object.end_datetime|date:"d/m/Y, H:i" }}</li>
                    <li>Владелец: {{ object.owner }}</li>
                    <li>Клиенты: {% for client in object.client_emails.all %} {{ client.email }}</li> {% endfor %}
                </ul>
                {% if user.is_superuser or user == object.owner %}
                <div class="mb-3">
                    <a href="{% url 'mailing:update_mailing' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'mailing:delete_mailing' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Удалить</a>
                </div>
                {% endif %}
                <div class="mb-3">
                    <a href="{% url 'mailing:mailing_page' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'website/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ title }}</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'mailing:mailing_page' %}"
                           class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'website/base.html' %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-2 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">{{ object.name|title }}</h6>
                </div>
                <div class="card-body">
                    <h6 class="card-title pricing-card-title">Время рассылки: {{ object.first_sending_time|date:"d/m/Y, H:i" }}</h6>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Периодичность: {{ object.period }}</li>
                        <li>Статус: {{ object.status }}</li>
                        <li>Владелец: {{ object.owner }}</li>
                        <li>След рассылка: {{ object.next_sending_time|date:"d/m/Y, H:i"|default:'Не заполнено'}}</li>
                    </ul>

                    <div class="mb-3">
                        {% if object.is_active %}
                        <a href="{% url 'mailing:toggle_activity' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-danger">Отключить</a>
                        {% else %}
                        <a href="{% url 'mailing:toggle_activity' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-success">Включить</a>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <a href="{% url 'logstatus:logs_page' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-warning">Логи</a>
                    </div>

                    <div class="mb-3">
                        <a href="{% url 'mailing:view_mailing' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-primary">Подробнее</a>
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
        {% if not user.is_staff %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">Новая рассылка</h6>
                </div>
                <div class="card-body">
                    <a href="{% url 'mailing:add_mailing' %}" class="w-120 btn btn-lg btn-outline-primary">Добавить</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>

{% endblock %}