blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [path("", cache_page(60)(BlogListView.as_view()), name="blog_page")]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("letters/", include("letters.urls", namespace="letters")),
    path("logstatus/", include("logstatus.urls", namespace="logstatus")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letters/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from letters.apps import MessagesConfig
from letters.views import LetterCreateView, LetterDeleteView, LetterDetailView, LetterListView, LetterUpdateView

app_name = MessagesConfig.name

urlpatterns = [
    path("", cache_page(60)(LetterListView.as_view()), name="letters_page"),
    path("view_letter/<int:pk>/", LetterDetailView.as_view(), name="view_letter"),
    path("add_letter/", LetterCreateView.as_view(), name="add_letter"),
    path("update_letter/<int:pk>/", LetterUpdateView.as_view(), name="update_letter"),
    path("delete_letter/<int:pk>/", LetterDeleteView.as_view(), name="delete_letter"),
]

letters/models.py
from django.conf import settings
from django.db import models

from config.settings import NULLABLE


class Letter(models.Model):
    """
    Модель Письма
    """

    letter_header = models.CharField(max_length=200, verbose_name="Тема письма")
    letter_body = models.TextField(verbose_name="Тело письма")
    created_at = models.DateField(**NULLABLE, auto_now_add=True, verbose_name="Дата создания")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self) -> str:
        return f"{self.letter_header}"

    class Meta:
        verbose_name = "письмо"
        verbose_name_plural = "письма"

letters/forms.py
from django import forms

from letters.models import Letter
from website.forms import StyleFormMixin


class LetterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Letter
        exclude = ("owner",)

letters/views.py
import typing

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from letters.forms import LetterForm
from letters.models import Letter


class LetterListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра сущностей"""

    model = Letter
    login_url = reverse_lazy("website:homepage")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Письма"
        return context

    def get_queryset(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class LetterDetailView(DetailView):
    """Контроллер для просмотра сущности"""

    model = Letter

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = self.object
        return context

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.owner != user:
            raise Http404("Доступ запрещен")
        return self.object


class LetterCreateView(UserPassesTestMixin, CreateView):
    """Контроллер для создания сущности"""

    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy("letters:letters_page")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Добавление письма"
        return context

    def form_valid(self, form: typing.Any) -> typing.Any:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self) -> typing.Any:
        return not self.request.user.groups.filter(name="manager")


class LetterUpdateView(UpdateView):
    """Контроллер для изменения сущности"""

    model = Letter
    form_class = LetterForm

    def get_success_url(self) -> typing.Any:
        return reverse("letters:view_letter", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Обновление письма"
        return context


class LetterDeleteView(DeleteView):
    """Контроллер для удаления сущности"""

    model = Letter
    success_url = reverse_lazy("letters:letters_page")

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Удаление письма"
        return context

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.owner != user:
            raise Http404("Доступ запрещен")
        return self.object

letters/templates/letters/letter_confirm_delete.html
{% extends 'website/base.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Удаление письма</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Точно удаляем {{ object|title }}?</p>
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Удалить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'letters:letters_page' %}" class="w-100 btn btn-lg btn-outline-primary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

letters/templates/letters/letter_detail.html
{% extends 'website/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object|title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Текст письма: {{ object.letter_body }}</li>
                    <li>Владелец: {{ object.owner }}</li>
                </ul>
                <div class="mb-3">
                    <a href="{% url 'letters:update_letter' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'letters:delete_letter' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Удалить</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'letters:letters_page' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

letters/templates/letters/letter_form.html
{% extends 'website/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ title }}</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'letters:letters_page' %}"
                           class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

letters/templates/letters/letter_list.html
{% extends 'website/base.html' %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">{{ object|capfirst }}</h6>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Дата создания: {{ object.created_at|date:"d/m/Y" }}</li>
                        <li>Владелец: {{ object.owner }}</li>
                    </ul>
                    <a href="{% url 'letters:view_letter' object.pk %}" class="w-120 btn btn-lg btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not user.is_staff %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">Новое письмо</h6>
                </div>
                <div class="card-body">
                    <a href="{% url 'letters:add_letter' %}" class="w-120 btn btn-lg btn-outline-primary">Добавить</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>

{% endblock %}