blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [path("", cache_page(60)(BlogListView.as_view()), name="blog_page")]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("letters/", include("letters.urls", namespace="letters")),
    path("logstatus/", include("logstatus.urls", namespace="logstatus")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileView, RegisterView, RestorePassword, Verification, logout_view

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("verification/", Verification.as_view(), name="verification"),
    path("restore_password/", RestorePassword.as_view(), name="restore_password"),
]

website/urls.py
from django.urls import path

from website.apps import WebsiteConfig
from website.views import ManagerListView, WebsiteListView, toggle_activity

app_name = WebsiteConfig.name

urlpatterns = [
    path("", WebsiteListView.as_view(), name="homepage"),
    path("manager/", ManagerListView.as_view(), name="manager"),
    path("activity/<int:pk>/", toggle_activity, name="managerpage"),
]

users/models.py
from typing import List

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Модель Пользователя
    """

    username = None
    email = models.EmailField(unique=True, verbose_name="почта")

    phone = models.CharField(max_length=35, null=True, blank=True, verbose_name="телефон")
    avatar = models.ImageField(upload_to="users/", null=True, blank=True, verbose_name="аватар")
    country = models.CharField(max_length=50, null=True, blank=True, verbose_name="страна")
    auth_token = models.CharField(max_length=30, default="", blank=True, null=True, verbose_name="ключ")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS: List[type] = []

users/forms.py
import typing

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    """Класс формы регистрации"""

    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(UserChangeForm):
    """Класс профиля пользователя"""

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "phone", "country", "avatar")

    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import typing

from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import UserProfileForm, UserRegisterForm
from users.models import User
from users.services import get_generated_key, send_key_mail, send_password_mail


def logout_view(request: typing.Any) -> typing.Any:
    """Контроллер для выхода из авторизации пользователя"""
    logout(request)
    return redirect("/")


class RegisterView(CreateView):
    """Контроллер для регистрации пользователя"""

    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"

    def form_valid(self, form: typing.Any) -> typing.Any:
        new_user = form.save()
        current_site = self.request.get_host()
        new_user.is_active = False
        new_user.auth_token = get_generated_key(5)
        new_user.save()
        send_key_mail(new_user.auth_toke, current_site, new_user.email)

        return super().form_valid(form)

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Регистрация"
        return context

    def get_success_url(self) -> typing.Any:
        return reverse("users:verification")


class ProfileView(UpdateView):
    """Контроллер для просмотра профиля пользователя"""

    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset: typing.Any = None) -> typing.Any:
        return self.request.user

    def get_context_data(self, **kwargs: typing.Any) -> typing.Any:
        context = super().get_context_data(**kwargs)
        context["title"] = "Мой профиль"
        return context


class Verification(TemplateView):
    """Контроллер для верификации пользователя"""

    def get(self, request: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        return render(request, "users/verification.html")

    def post(self, request: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        code = request.POST.get("auth_token")
        user = get_object_or_404(User, auth_token=code)

        if not user.is_active:
            user.is_active = True
            user.save()
        return redirect("users:login")


class RestorePassword(TemplateView):
    """Контроллер для восстановления пароля пользователя"""

    def get(self, request: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        return render(request, "users/new_password.html")

    def post(self, request: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> typing.Any:
        mail = request.POST.get("email")
        user = get_object_or_404(User, email=mail)
        new_password = get_generated_key(15)
        send_password_mail(new_password, user.email)
        user.set_password(new_password)
        user.save()
        return redirect("users:login")

users/templates/users/login.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" action="" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Вход</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Войти</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'website:homepage' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'users:register' %}" class="w-100 btn btn-lg btn-outline-danger">Регистрация</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'users:restore_password' %}" class="w-100 btn btn-lg btn-outline-danger">Забыли пароль</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

users/templates/users/new_password.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" action="" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Создание нового пароля</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email">Введите свою почту (новый пароль будет отправлен на нее)</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Почта"
                               required>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Восстановить пароль</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'website:homepage' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" action="" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Регистрация</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Зарегистрироваться</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'website:homepage' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" action="" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Профиль</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'website:homepage' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

users/templates/users/verification.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" action="" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Верификация</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="auth_token">Ключ</label>
                        <input type="text" name="auth_token" class="form-control" id="auth_token" placeholder="Ключ"
                               required>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Отправить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'website:homepage' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}